tarsier_admin:
    resource: "@TarsierAdminBundle/Controller/"
    type:     annotation
    prefix:   /

tarsier_home:
    resource: "@TarsierHomeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
