tarsier_mosquito:
    resource: "@TarsierMosquitoBundle/Controller/"
    type:     annotation
    prefix:   /

tarsier_wx:
    resource: "@TarsierWxBundle/Controller/"
    type:     annotation
    prefix:   /

tarsier_admin:
    resource: "@TarsierAdminBundle/Controller/"
    type:     annotation
    prefix:   /

tarsier_home:
    resource: "@TarsierHomeBundle/Controller/"
    type:     annotation
    prefix:   /

