<?php

namespace Tarsier\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleImgRepository extends EntityRepository
{

    private function getArticleImgByArticleIdObject($article_ids){
       return $this->getEntityManager()
            ->createQuery('SELECT a FROM TarsierHomeBundle:articleimg a WHERE a.article_id IN(:article_id)  ')
            ->setParameters(array('article_id'=>$article_ids));
    }

    public function getArticleImgByArticleId($article_ids){
        return $this->getArticleImgByArticleIdObject($article_ids)
            ->setMaxResults(1)
            ->getResult();
    }

    public function getArticleImgByArticleIds($article_ids){
        return $this->getArticleImgByArticleIdObject($article_ids)->getResult();

    }

}
