<?php

namespace Tarsier\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function findTopArticle()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM TarsierHomeBundle:article a ORDER BY a.top DESC,a.id DESC')
            ->setMaxResults(1)
            ->getResult();
    }

    public function findIndexArticle($id,$nums=3)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM TarsierHomeBundle:article a WHERE a.id <> :id ORDER BY a.top DESC,a.id DESC')
            ->setParameters(array('id'=>$id))
            ->setMaxResults($nums)
            ->getResult();
    }

    public function getHotArticle($limit=10){
        $dql=$this->getEntityManager()
            ->createQueryBuilder()
            ->select('a.title,a.id')
            ->from('TarsierHomeBundle:article','a')
            ->where("a.status=:status")
            ->orderBy('a.click','DESC')
            ->getDQL();

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('status','1')
            ->setMaxResults(intval($limit))
            ->getResult();
    }

}
