<?php

namespace Tarsier\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function findTopArticle()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM TarsierHomeBundle:article a WHERE a.status=1 ORDER BY a.top DESC,a.id DESC')
            ->setMaxResults(1)
            ->getResult();
    }

    public function findIndexArticle($id,$nums=3)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM TarsierHomeBundle:article a WHERE a.id <> :id AND a.status=1 ORDER BY a.top DESC,a.id DESC')
            ->setParameters(array('id'=>$id))
            ->setMaxResults($nums)
            ->getResult();
    }

    public function getHotArticle($limit=10){
        $dql=$this->getEntityManager()
            ->createQueryBuilder()
            ->select('a.title,a.id,a.create_time,a.click')
            ->from('TarsierHomeBundle:article','a')
            ->where("a.status=:status")
            ->orderBy('a.click','DESC')
            ->getDQL();

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('status','1')
            ->setMaxResults(intval($limit))
            ->getResult();
    }

    public function findAllArticle(){
        $dql="SELECT a FROM TarsierHomeBundle:article a ORDER BY a.id DESC";
        $query=$this->getEntityManager()->createQuery($dql);
        return $query;
    }

    public function findRssArticle($nums=10)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a.id,a.title,a.content,a.create_time FROM TarsierHomeBundle:article a WHERE a.status=1 ORDER BY a.create_time DESC,a.top DESC')
            ->setMaxResults($nums)
            ->getArrayResult();
    }


    public function getArticleBySearch($mode){

        $where='';
        $where=['title'=>'a.title','tags'=>'t.name','user'=>'u.username'];
        foreach ($mode as $k=>$v) {
            if(!empty($v))
                $mode[$where[$k]]="(".join(' OR ',str_replace("$k",$where[$k],$v)).")";
            unset($mode[$k]);
        }

        $mode=join(" AND ",$mode);
        $dql="select a,t,u from TarsierHomeBundle:article a LEFT JOIN a.tag t LEFT JOIN a.user u where $mode AND a.status=1 ORDER BY a.sort DESC";
        $query=$this->getEntityManager()->createQuery($dql);

        return $query;
    }

}
