<?php

namespace Tarsier\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendlinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendlinkRepository extends EntityRepository
{

    public function findAllFriendlink(){
        $dql="SELECT f FROM TarsierHomeBundle:friendlink f ORDER BY f.sort DESC";
        $query=$this->getEntityManager()->createQuery($dql);
        return $query;
    }

}
