<?php

namespace Tarsier\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QrrecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QrrecordRepository extends EntityRepository
{
}
