<?php

namespace Tarsier\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends EntityRepository
{
    public function getArticleByName($nav_tags){
        $dql="select a,t from TarsierHomeBundle:article a LEFT JOIN a.tag t where t.name='$nav_tags' AND a.status=1 ORDER BY a.sort DESC";
        $query=$this->getEntityManager()->createQuery($dql);
        return $query;
    }
}
